import {ErrorType, HyperFormula, SheetNameAlreadyTakenError} from '../../../src'
import {plPL} from '../../../src/i18n/languages'
import {adr, detailedError} from '../testUtils'

describe('Adding sheet - checking if its possible', () => {
  it('yes', () => {
    const engine = HyperFormula.buildEmpty()

    expect(engine.isItPossibleToAddSheet('Sheet1')).toEqual(true)
    expect(engine.isItPossibleToAddSheet('~`!@#$%^&*()_-+_=/|?{}[]\\"')).toEqual(true)
  })

  it('no', () => {
    const engine = HyperFormula.buildFromSheets({
      Sheet1: [],
      Foo: [],
    })

    expect(engine.isItPossibleToAddSheet('Sheet1')).toEqual(false)
    expect(engine.isItPossibleToAddSheet('Foo')).toEqual(false)
  })
})

describe('add sheet to engine', () => {
  it('should add sheet to empty engine', function() {
    const engine = HyperFormula.buildEmpty()

    engine.addSheet()

    expect(engine.sheetMapping.numberOfSheets()).toEqual(1)
    expect(Array.from(engine.sheetMapping.displayNames())).toEqual(['Sheet1'])
  })

  it('should add sheet to engine with one sheet', function() {
    const engine = HyperFormula.buildFromArray([
      ['foo'],
    ])

    engine.addSheet()

    expect(engine.sheetMapping.numberOfSheets()).toEqual(2)
    expect(Array.from(engine.sheetMapping.displayNames())).toEqual(['Sheet1', 'Sheet2'])
  })

  it('should be possible to fetch empty cell from newly added sheet', function() {
    const engine = HyperFormula.buildEmpty()

    engine.addSheet()

    expect(engine.getCellValue(adr('A1', 0))).toBe(null)
  })

  it('should add sheet with translated sheet name', function() {
    HyperFormula.registerLanguage('plPL', plPL)
    const engine = HyperFormula.buildEmpty({language: 'plPL'})

    engine.addSheet()

    expect(engine.sheetMapping.numberOfSheets()).toEqual(1)
    expect(Array.from(engine.sheetMapping.displayNames())).toEqual(['Arkusz1'])
  })

  it('should add sheet with given name', function() {
    const engine = HyperFormula.buildEmpty()

    engine.addSheet('foo')

    expect(engine.sheetMapping.numberOfSheets()).toEqual(1)
    expect(Array.from(engine.sheetMapping.displayNames())).toEqual(['foo'])
  })

  it('cannot add another sheet with same lowercased name', function() {
    const engine = HyperFormula.buildEmpty()
    engine.addSheet('foo')

    expect(() => {
      engine.addSheet('FOO')
    }).toThrowError(/already exists/)
    expect(engine.sheetMapping.numberOfSheets()).toEqual(1)
    expect(Array.from(engine.sheetMapping.displayNames())).toEqual(['foo'])
  })

  it('should return given name', function() {
    const engine = HyperFormula.buildEmpty()

    const sheetName = engine.addSheet('foo')

    expect(sheetName).toEqual('foo')

  })

  it('should return autogenerated name', function() {
    const engine = HyperFormula.buildEmpty()

    const sheetName = engine.addSheet()

    expect(sheetName).toEqual('Sheet1')
  })

  it('should throw error when sheet name is already taken', () => {
    const engine = HyperFormula.buildEmpty()
    engine.addSheet('bar')

    expect(() => {
      engine.addSheet('bar')
    }).toThrow(new SheetNameAlreadyTakenError('bar'))
  })

  it('recalculates the cells referencing the new sheet (#1116)', () => {
    const  engine = HyperFormula.buildEmpty()
    const table1Name = 'table1'
    const table2Name = 'table2'

    engine.addSheet(table1Name)
    engine.setCellContents(adr('A1', engine.getSheetId(table1Name)), `='${table2Name}'!A1`)

    expect(engine.getCellValue(adr('A1', engine.getSheetId(table1Name)))).toEqualError(detailedError(ErrorType.REF))

    engine.addSheet(table2Name)
    engine.setCellContents(adr('A1', engine.getSheetId(table2Name)), 10)

    expect(engine.getCellValue(adr('A1', engine.getSheetId(table1Name)))).toBe(10)
  })

  it('#1116 - batch', () => {
    const  engine = HyperFormula.buildEmpty()
    const table1Name = 'table1'
    const table2Name = 'table2'

    engine.batch(() => {
      engine.addSheet(table1Name)
      engine.setCellContents(adr('A1', engine.getSheetId(table1Name)), `='${table2Name}'!A1`)

      engine.addSheet(table2Name)
      engine.setCellContents(adr('A1', engine.getSheetId(table2Name)), 10)
    })

    expect(engine.getCellValue(adr('A1', engine.getSheetId(table1Name)))).toBe(10)
  })

  it('#1116 - suspend', () => {
    const  engine = HyperFormula.buildEmpty()
    const table1Name = 'table1'
    const table2Name = 'table2'

    engine.suspendEvaluation()

    engine.addSheet(table1Name)
    engine.setCellContents(adr('A1', engine.getSheetId(table1Name)), `='${table2Name}'!A1`)

    engine.addSheet(table2Name)
    engine.setCellContents(adr('A1', engine.getSheetId(table2Name)), 10)

    engine.resumeEvaluation()

    expect(engine.getCellValue(adr('A1', engine.getSheetId(table1Name)))).toBe(10)
  })

  it('#1116 - rebuild', () => {
    const  engine = HyperFormula.buildEmpty()
    const table1Name = 'table1'
    const table2Name = 'table2'

    engine.addSheet(table1Name)
    engine.setCellContents(adr('A1', engine.getSheetId(table1Name)), `='${table2Name}'!A1`)

    expect(engine.getCellValue(adr('A1', engine.getSheetId(table1Name)))).toEqualError(detailedError(ErrorType.REF))

    engine.addSheet(table2Name)
    engine.setCellContents(adr('A1', engine.getSheetId(table2Name)), 10)

    engine.rebuildAndRecalculate()

    expect(engine.getCellValue(adr('A1', engine.getSheetId(table1Name)))).toBe(10)
  })
})
