export enum StatType {
  /* build engine */
  BUILD_ENGINE_TOTAL = 'BUILD_ENGINE_TOTAL',
  PARSER = 'PARSER',
  GRAPH_BUILD = 'GRAPH_BUILD',
  TOP_SORT = 'TOP_SORT',
  MATRIX_DETECTION = 'MATRIX_DETECTION',
  BUILD_COLUMN_INDEX = 'BUILD_COLUMN_INDEX',
  EVALUATION = 'EVALUATION',
  VLOOKUP = 'VLOOKUP',
  /* crud adjustments */
  TRANSFORM_ASTS = 'TRANSFORM_ASTS',
  TRANSFORM_ASTS_POSTPONED = 'TRANSFORM_ASTS_POSTPONED',
  ADJUSTING_ADDRESS_MAPPING = 'ADJUSTING_ADDRESS_MAPPING',
  ADJUSTING_MATRIX_MAPPING = 'ADJUSTING_MATRIX_MAPPING',
  ADJUSTING_RANGES = 'ADJUSTING_RANGES',
  ADJUSTING_GRAPH = 'ADJUSTING_GRAPH',
  /* criterion cache */
  CRITERION_FUNCTION_FULL_CACHE_USED = 'CRITERION_FUNCTION_FULL_CACHE_USED',
  CRITERION_FUNCTION_PARTIAL_CACHE_USED = 'CRITERION_FUNCTION_PARTIAL_CACHE_USED',
}
