name: Bug report
description: Is something not working? Report a bug to help us improve.
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: describe-bug
    attributes:
      label: Description
      description: Describe what happens, and specify the exact steps to reproduce the problem. If we can't recreate the issue, we'll close it down.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Video or screenshots
      description: Add a screenshot or a short video that clearly illustrates the problem.
  - type: input
    id: demo
    attributes:
      label: Demo
      description: Add a link to a demo that will let us reproduce the bug. Use StackBlitz, CodeSandbox, CodePen, JSFiddle, or any other online sandbox.
    validations:
      required: true
  - type: input
    id: hf-version
    attributes:
      label: HyperFormula version
      description: Which version of HyperFormula are you using?
    validations:
      required: true
  - type: input
    id: framework
    attributes:
      label: Your framework
      description: What framework are you using? For example, React 16.0, Angular v15 or Vue 3.
  - type: input
    id: environment
    attributes:
      label: Your environment
      description: What's your browser and operating system? For example, Chrome 90 on macOS 11.3.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report the issue! ❤️
