/**
 * @license
 * Copyright (c) 2025 Handsoncode. All rights reserved.
 */

/**
 * HF-249 bullet 3 — generates the built-in functions guide page `docs/guide/built-in-functions.md` from
 * HyperFormula's public API (single source of truth). Reads the committed template
 * `built-in-functions.tmpl.md` (hand-written prose + empty `AUTOGENERATED:CATEGORIES` and `AUTOGENERATED:FUNCTIONS`
 * markers), splices the generated table of contents and function sections into their marker regions, and writes
 * `built-in-functions.md` — which is **gitignored**, being a pure build product with no committed copy to drift.
 * Dev-only; never shipped (`tsconfig.json` `include` is `["src"]`). Runs as the first step of `docs:build`/`docs:dev`
 * (also `npm run docs:generate-function-docs`), so the page is regenerated on every build and cannot drift from the
 * catalogue.
 */

import * as fs from 'fs'
import * as path from 'path'
import {HyperFormula} from '../src'
import {renderBuiltinFunctionsMarkdown, spliceBuiltinFunctionsMarkdown} from './renderBuiltinFunctionsTable'

const REPO_ROOT = path.resolve(__dirname, '..')
const TEMPLATE_PATH = path.join(REPO_ROOT, 'docs/guide/built-in-functions.tmpl.md')
const DOC_PATH = path.join(REPO_ROOT, 'docs/guide/built-in-functions.md')
const LANGUAGE = 'enGB'
/**
 * The GPLv3 key, which grants the complete function set. The metadata API is instance-scoped, so this page is
 * generated against an engine rather than against the package, and the engine's entitlement therefore decides which
 * functions reach the page. Naming the fully-entitled key here — instead of leaving it to whatever key the build
 * environment happens to supply — is what keeps the published reference documenting every built-in rather than
 * narrowing to one tier (HF-349).
 */
const LICENSE_KEY = 'gpl-v3'

/** Reads the committed template and returns the page with both generated regions spliced in. */
function buildUpdatedFile(): string {
  const engine = HyperFormula.buildEmpty({language: LANGUAGE, licenseKey: LICENSE_KEY})
  const entries = engine.getAvailableFunctions()
  const detailsFor = (canonicalName: string) => engine.getFunctionDetails(canonicalName)
  const generated = renderBuiltinFunctionsMarkdown(entries, detailsFor)
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8')
  return spliceBuiltinFunctionsMarkdown(template, generated)
}

/** Generates the guide page from the template + current catalogue. */
function main(): void {
  fs.writeFileSync(DOC_PATH, buildUpdatedFile(), 'utf8')
  process.stdout.write('built-in-functions.md generated from template.\n')
}

main()
