/**
 * @license
 * Copyright (c) 2025 Handsoncode. All rights reserved.
 */

import {FUNCTION_CATEGORIES, FunctionCategory, FunctionDetails, FunctionListEntry} from '../src/interpreter/functionMetadata/FunctionDescription'
import {formatFunctionSyntax} from './formatFunctionSyntax'

/** Opening marker; the generated table region begins on the next line. */
export const FUNCTIONS_TABLE_START = '<!-- AUTOGENERATED:FUNCTIONS:START -->'
/** Closing marker; everything after it (e.g. footnote definitions) is hand-maintained. */
export const FUNCTIONS_TABLE_END = '<!-- AUTOGENERATED:FUNCTIONS:END -->'

/**
 * Deterministic, environment-independent ordering for function names (never ambient locale). Intentionally
 * pinned to English: the generated table is English-only, so ordering must not depend on the host locale. (The
 * public API's list ordering is language-derived; this renderer's is deliberately English-only.)
 */
const COLLATOR = new Intl.Collator('en', {sensitivity: 'variant', caseFirst: 'upper'})

/** Escapes only the table-breaking pipe; all other markdown (links, code, `<br>`, footnotes) is verbatim. */
function escapeCell(text: string): string {
  return text.replace(/\r?\n/g, '<br>').replace(/\|/g, '\\|')
}

/**
 * Renders the built-in functions table as markdown: one `### Category` section per category (in the canonical
 * `FUNCTION_CATEGORIES` order), each a 3-column table (Function ID | Description | Syntax). Rows are sorted by a
 * pinned collator for deterministic, byte-idempotent output, with the canonical name as a stable tiebreaker for
 * entries that share a localized name (mirrors `HyperFormula.buildAvailableFunctions`). Reads only the passed
 * entries + details provider, so it is independent of how the catalogue is stored (forward-compatible with a
 * per-function file split).
 *
 * @param {FunctionListEntry[]} entries - the function set to document (e.g. `HyperFormula.getAvailableFunctions`)
 * @param {(canonicalName: string) => FunctionDetails | undefined} detailsFor - resolves a function's details
 * @returns {string} the markdown for the table region (no surrounding markers, LF, trailing newline)
 * @throws {Error} when a listed entry has no resolvable details
 */
export function renderBuiltinFunctionsTable(
  entries: FunctionListEntry[],
  detailsFor: (canonicalName: string) => FunctionDetails | undefined,
): string {
  const byCategory = new Map<FunctionCategory, FunctionListEntry[]>()
  for (const entry of entries) {
    if (entry.category === undefined) {
      continue
    }
    const bucket = byCategory.get(entry.category) ?? []
    bucket.push(entry)
    byCategory.set(entry.category, bucket)
  }

  const sections: string[] = []
  for (const category of FUNCTION_CATEGORIES) {
    const bucket = byCategory.get(category)
    if (bucket === undefined || bucket.length === 0) {
      continue
    }
    bucket.sort((a, b) => COLLATOR.compare(a.localizedName, b.localizedName) || COLLATOR.compare(a.canonicalName, b.canonicalName))
    const rows = bucket.map(entry => {
      const details = detailsFor(entry.canonicalName)
      if (details === undefined) {
        throw new Error(`No details for listed function "${entry.canonicalName}"`)
      }
      const syntax = formatFunctionSyntax(details.localizedName, details.parameters, details.repeatLastArgs)
      const anchor = `<a id="${entry.canonicalName}"></a>`
      return `| ${anchor}${escapeCell(entry.localizedName)} | ${escapeCell(entry.shortDescription)} | ${escapeCell(syntax)} |`
    })
    sections.push(`### ${category}\n\n| Function ID | Description | Syntax |\n|:---|:---|:---|\n${rows.join('\n')}`)
  }

  return sections.join('\n\n') + '\n'
}

/**
 * Replaces the content between the autogenerated markers in a markdown file, preserving everything outside them
 * (intro prose, footnote definitions). Fails loud on a malformed marker state rather than clobbering the file.
 *
 * @param {string} fileContent - the full current file content
 * @param {string} generatedSection - the markdown to place between the markers (from renderBuiltinFunctionsTable)
 * @returns {string} the updated file content
 * @throws {Error} when either marker is missing, duplicated, or out of order
 */
export function spliceFunctionsTable(fileContent: string, generatedSection: string): string {
  const startCount = fileContent.split(FUNCTIONS_TABLE_START).length - 1
  const endCount = fileContent.split(FUNCTIONS_TABLE_END).length - 1
  if (startCount !== 1 || endCount !== 1) {
    throw new Error(`Expected exactly one START and one END marker, found ${startCount}/${endCount}`)
  }
  const startIdx = fileContent.indexOf(FUNCTIONS_TABLE_START)
  const endIdx = fileContent.indexOf(FUNCTIONS_TABLE_END)
  if (endIdx < startIdx) {
    throw new Error('END marker appears before START marker')
  }
  const before = fileContent.slice(0, startIdx + FUNCTIONS_TABLE_START.length)
  const after = fileContent.slice(endIdx)
  return `${before}\n${generatedSection}\n${after}`
}
