/**
 * @license
 * Copyright (c) 2025 Handsoncode. All rights reserved.
 */

import {CUSTOM_FUNCTION_CATEGORY, DocumentedFunctionCategory, FUNCTION_CATEGORIES, FunctionDetails, FunctionListEntry} from '../src/interpreter/functionMetadata/FunctionDescription'
import {formatFunctionSyntax} from './formatFunctionSyntax'

/** Opening marker; the generated table region begins on the next line. */
export const FUNCTIONS_TABLE_START = '<!-- AUTOGENERATED:FUNCTIONS:START -->'
/**
 * Closing marker; anything the template puts after it is preserved verbatim. The template currently ends on this
 * marker, so there is no tail region: a description needing a footnote must inline the note (as EDATE and EOMONTH
 * do with their OpenDocument caveat) rather than emit a `[^ref]` that has nowhere to be defined.
 */
export const FUNCTIONS_TABLE_END = '<!-- AUTOGENERATED:FUNCTIONS:END -->'

/**
 * Deterministic, environment-independent ordering for function names (never ambient locale). Intentionally
 * pinned to English: the generated table is English-only, so ordering must not depend on the host locale. (The
 * public API's list ordering is language-derived; this renderer's is deliberately English-only.)
 */
const COLLATOR = new Intl.Collator('en', {sensitivity: 'variant', caseFirst: 'upper'})

/**
 * Escapes the table-breaking pipe and the backslash that would otherwise consume the pipe's own
 * escape; all other markdown (links, code, `<br>`, footnotes) is verbatim. Both are replaced in a
 * single pass, so an input backslash can never end up escaping a backslash we just inserted
 * (escaping `|` alone leaves `a\|b` rendering as a cell break — CodeQL js/incomplete-sanitization).
 *
 * Line breaks need no handling: a catalogue string spells them as a literal `<br>` (see
 * `FunctionDoc.shortDescription`), so none of the strings that reach here — the localized name, the shortDescription,
 * or the syntax built from the parameter names — can contain a raw newline. A newline-to-`<br>` pass would be dead
 * code; keep the `<br>` convention in the catalogue instead.
 *
 * @param {string} text - the cell text to escape
 */
function escapeCell(text: string): string {
  return text.replace(/[\\|]/g, '\\$&')
}

/**
 * Renders the built-in functions table as markdown: one `### Category` section per category (in the canonical
 * `FUNCTION_CATEGORIES` order), each a 3-column table (Function ID | Description | Syntax). Rows are sorted by a
 * pinned collator for deterministic, byte-idempotent output, with the canonical name as a stable tiebreaker for
 * entries that share a localized name (mirrors `HyperFormula.buildAvailableFunctions`). Reads only the passed
 * entries + details provider, so it is independent of how the catalogue is stored (forward-compatible with a
 * per-function file split).
 *
 * Only the documented categories get a section, so every entry passed in must declare one: the page is generated from
 * the built-in catalogue, where `category` is a [[DocumentedFunctionCategory]] by type. A `'Custom'` entry is rejected
 * rather than skipped — silently dropping it would leave the page short of a row while the printed function total,
 * which is computed independently in `docs/.vuepress/config.js`, still claimed it.
 *
 * @param {FunctionListEntry[]} entries - the function set to document (e.g. `HyperFormula.getAvailableFunctions`)
 * @param {(canonicalName: string) => FunctionDetails | undefined} detailsFor - resolves a function's details
 * @returns {string} the markdown for the table region (no surrounding markers, LF, trailing newline)
 * @throws {Error} when a listed entry has no resolvable details
 * @throws {Error} when a listed entry reports a category with no section on the page (i.e. `'Custom'`)
 */
export function renderBuiltinFunctionsTable(
  entries: FunctionListEntry[],
  detailsFor: (canonicalName: string) => FunctionDetails | undefined,
): string {
  const byCategory = new Map<DocumentedFunctionCategory, FunctionListEntry[]>()
  for (const entry of entries) {
    if (entry.category === CUSTOM_FUNCTION_CATEGORY) {
      throw new Error(`Function "${entry.canonicalName}" reports category "${entry.category}", which has no section on the generated page; the page is generated from the built-in catalogue only.`)
    }
    const bucket = byCategory.get(entry.category) ?? []
    bucket.push(entry)
    byCategory.set(entry.category, bucket)
  }

  const sections: string[] = []
  for (const category of FUNCTION_CATEGORIES) {
    const bucket = byCategory.get(category)
    if (bucket === undefined || bucket.length === 0) {
      continue
    }
    bucket.sort((a, b) => COLLATOR.compare(a.localizedName, b.localizedName) || COLLATOR.compare(a.canonicalName, b.canonicalName))
    const rows = bucket.map(entry => {
      const details = detailsFor(entry.canonicalName)
      if (details === undefined) {
        throw new Error(`No details for listed function "${entry.canonicalName}"`)
      }
      const syntax = formatFunctionSyntax(details.localizedName, details.parameters, details.repeatLastArgs)
      const anchor = `<a id="${entry.canonicalName}"></a>`
      return `| ${anchor}${escapeCell(entry.localizedName)} | ${escapeCell(entry.shortDescription)} | ${escapeCell(syntax)} |`
    })
    sections.push(`### ${category}\n\n| Function ID | Description | Syntax |\n|:---|:---|:---|\n${rows.join('\n')}`)
  }

  return sections.join('\n\n') + '\n'
}

/**
 * Replaces the content between the autogenerated markers in a markdown file, preserving everything outside them
 * (intro prose, footnote definitions). Fails loud on a malformed marker state rather than clobbering the file.
 *
 * @param {string} fileContent - the full current file content
 * @param {string} generatedSection - the markdown to place between the markers (from renderBuiltinFunctionsTable)
 * @returns {string} the updated file content
 * @throws {Error} when either marker is missing, duplicated, or out of order
 */
export function spliceFunctionsTable(fileContent: string, generatedSection: string): string {
  const startCount = fileContent.split(FUNCTIONS_TABLE_START).length - 1
  const endCount = fileContent.split(FUNCTIONS_TABLE_END).length - 1
  if (startCount !== 1 || endCount !== 1) {
    throw new Error(`Expected exactly one START and one END marker, found ${startCount}/${endCount}`)
  }
  const startIdx = fileContent.indexOf(FUNCTIONS_TABLE_START)
  const endIdx = fileContent.indexOf(FUNCTIONS_TABLE_END)
  if (endIdx < startIdx) {
    throw new Error('END marker appears before START marker')
  }
  const before = fileContent.slice(0, startIdx + FUNCTIONS_TABLE_START.length)
  const after = fileContent.slice(endIdx)
  return `${before}\n${generatedSection}\n${after}`
}
