/**
 * @license
 * Copyright (c) 2025 Handsoncode. All rights reserved.
 */

import {FunctionDoc} from '../FunctionDescription'

/**
 * Catalogue entries for the "Financial" category. Generated from `docs/guide/built-in-functions.md` by
 * a one-time migration script (since removed).
 */
export const FINANCIAL_DOCS: Record<string, FunctionDoc> = {
  CUMIPMT: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the cumulative interest paid on a loan between a start period and an end period.',
    parameters: [{name: 'rate', description: 'The interest rate per period.'}, {name: 'nper', description: 'The total number of payment periods.'}, {name: 'pv', description: 'The present value, i.e. the loan principal.'}, {name: 'start', description: 'The first period to include in the calculation, numbered starting at 1.'}, {name: 'end', description: 'The last period to include in the calculation; must not be smaller than start.'}, {name: 'type', description: 'When payments are due: 0 for the end of each period, 1 for the beginning.'}],
    examples: ['=CUMIPMT(0.05/12, 60, 20000, 1, 12, 0)', '=CUMIPMT(0.04/12, 360, 200000, 13, 24, 1)'],
  },
  CUMPRINC: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the cumulative principal paid on a loan between a start period and an end period.',
    parameters: [{name: 'rate', description: 'The interest rate per period.'}, {name: 'nper', description: 'The total number of payment periods.'}, {name: 'pv', description: 'The present value, i.e. the loan principal.'}, {name: 'start', description: 'The first period to include in the calculation, numbered starting at 1.'}, {name: 'end', description: 'The last period to include in the calculation; must not be smaller than start.'}, {name: 'type', description: 'When payments are due: 0 for the end of each period, 1 for the beginning.'}],
    examples: ['=CUMPRINC(0.05/12, 60, 20000, 1, 12, 0)', '=CUMPRINC(0.04/12, 360, 200000, 13, 24, 1)'],
  },
  DB: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the depreciation of an asset for a period using the fixed-declining balance method.',
    parameters: [{name: 'cost', description: 'The initial cost of the asset.'}, {name: 'salvage', description: 'The value of the asset at the end of its depreciation.'}, {name: 'life', description: 'The number of periods over which the asset is depreciated.'}, {name: 'period', description: 'The period, in the same units as life, for which depreciation is calculated.'}, {name: 'month', description: 'The number of months in the first year; defaults to 12 (a full year).'}],
    examples: ['=DB(10000, 1000, 6, 2)', '=DB(10000, 1000, 6, 1, 7)'],
  },
  DDB: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the depreciation of an asset for a period using the double-declining balance method.',
    parameters: [{name: 'cost', description: 'The initial cost of the asset.'}, {name: 'salvage', description: 'The value of the asset at the end of its depreciation.'}, {name: 'life', description: 'The number of periods over which the asset is depreciated.'}, {name: 'period', description: 'The period, in the same units as life, for which depreciation is calculated.'}, {name: 'factor', description: 'The rate at which the balance declines; defaults to 2 (double-declining).'}],
    examples: ['=DDB(10000, 1000, 6, 2)', '=DDB(10000, 1000, 6, 1, 1.5)'],
  },
  DOLLARDE: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Converts a price entered with a special notation to a price displayed as a decimal number.',
    parameters: [{name: 'price', description: 'The price expressed as an integer part plus a fractional part, e.g. 1.02 for 1 and 2/16.'}, {name: 'fraction', description: 'The denominator used in the fractional notation, e.g. 16 for sixteenths.'}],
    examples: ['=DOLLARDE(1.02, 16)', '=DOLLARDE(1.1, 32)'],
  },
  DOLLARFR: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Converts a price displayed as a decimal number to a price entered with a special notation.',
    parameters: [{name: 'price', description: 'The price expressed as a decimal number.'}, {name: 'fraction', description: 'The denominator to use in the fractional notation, e.g. 16 for sixteenths.'}],
    examples: ['=DOLLARFR(1.125, 16)', '=DOLLARFR(1.3, 32)'],
  },
  EFFECT: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Calculates the effective annual interest rate from a nominal interest rate and the number of compounding periods per year.',
    parameters: [{name: 'nominal_rate', description: 'The nominal (stated) annual interest rate.'}, {name: 'npery', description: 'The number of compounding periods per year.'}],
    examples: ['=EFFECT(0.1, 4)', '=EFFECT(0.08, 12)'],
  },
  FV: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the future value of an investment.',
    parameters: [{name: 'rate', description: 'The interest rate per period.'}, {name: 'nper', description: 'The total number of payment periods.'}, {name: 'pmt', description: 'The payment made each period; paid-out amounts are negative.'}, {name: 'pv', description: 'The present value, i.e. the lump-sum amount the future payments are worth right now; defaults to 0.'}, {name: 'type', description: 'When payments are due: 0 for the end of each period, 1 for the beginning; defaults to 0.'}],
    examples: ['=FV(0.05/12, 60, -100)', '=FV(0.06/12, 24, -200, -500, 1)'],
  },
  FVSCHEDULE: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the future value of an investment based on a rate schedule.',
    parameters: [{name: 'pv', description: 'The initial present value of the investment.'}, {name: 'schedule', description: 'A range of interest rates applied successively over each period.'}],
    examples: ['=FVSCHEDULE(1000, A1:A3)', '=FVSCHEDULE(5000, B2:B5)'],
  },
  IPMT: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the interest portion of a given loan payment in a given payment period.',
    parameters: [{name: 'rate', description: 'The interest rate per period.'}, {name: 'per', description: 'The period, between 1 and nper, for which the interest portion is calculated.'}, {name: 'nper', description: 'The total number of payment periods.'}, {name: 'pv', description: 'The present value, i.e. the loan principal.'}, {name: 'fv', description: 'The future value, i.e. the desired cash balance after the last payment; defaults to 0.'}, {name: 'type', description: 'When payments are due: 0 for the end of each period, 1 for the beginning; defaults to 0.'}],
    examples: ['=IPMT(0.05/12, 1, 60, 20000)', '=IPMT(0.04/12, 12, 360, 200000, 0, 1)'],
  },
  IRR: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the internal rate of return for a series of cash flows.',
    parameters: [{name: 'values', description: 'A range of cash flow values; must contain at least one negative and one positive value.'}, {name: 'guess', description: 'An estimated rate used as the starting point for the iterative calculation; defaults to 0.1 (10%).'}],
    examples: ['=IRR(A1:A5)', '=IRR(A1:A5, 0.2)'],
  },
  ISPMT: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the interest paid for a given period of an investment with equal principal payments.',
    parameters: [{name: 'rate', description: 'The interest rate per period.'}, {name: 'per', description: 'The period for which the interest is calculated.'}, {name: 'nper', description: 'The total number of payment periods.'}, {name: 'value', description: 'The present value, i.e. the loan principal.'}],
    examples: ['=ISPMT(0.05/12, 1, 60, 20000)', '=ISPMT(0.04/12, 12, 360, 200000)'],
  },
  MIRR: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the modified internal rate of return for a series of cash flows.',
    parameters: [{name: 'flows', description: 'A range of cash flow values; must contain at least one negative and one positive value.'}, {name: 'f_rate', description: 'The finance rate paid on the money used in the negative cash flows.'}, {name: 'r_rate', description: 'The reinvestment rate received on the positive cash flows.'}],
    examples: ['=MIRR(A1:A5, 0.08, 0.1)', '=MIRR(B2:B6, 0.06, 0.12)'],
  },
  NOMINAL: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the nominal interest rate.',
    parameters: [{name: 'effect_rate', description: 'The effective annual interest rate.'}, {name: 'npery', description: 'The number of compounding periods per year.'}],
    examples: ['=NOMINAL(0.1, 4)', '=NOMINAL(0.08, 12)'],
  },
  NPER: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the number of periods for an investment assuming periodic, constant payments and a constant interest rate.',
    parameters: [{name: 'rate', description: 'The interest rate per period.'}, {name: 'pmt', description: 'The payment made each period; paid-out amounts are negative.'}, {name: 'pv', description: 'The present value, i.e. the loan principal or initial investment.'}, {name: 'fv', description: 'The future value, i.e. the desired cash balance after the last payment; defaults to 0.'}, {name: 'type', description: 'When payments are due: 0 for the end of each period, 1 for the beginning; defaults to 0.'}],
    examples: ['=NPER(0.05/12, -100, 5000)', '=NPER(0.04/12, -200, 8000, 0, 1)'],
  },
  NPV: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns net present value.',
    parameters: [{name: 'rate', description: 'The discount rate applied over one period.'}, {name: 'value1', description: 'A cash flow value, cell reference, or range occurring at the end of a period. Further cash flow values can be passed as additional arguments.'}],
    examples: ['=NPV(0.1, -1000, 300, 400, 500)', '=NPV(0.08, A1:A5)'],
  },
  PDURATION: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns number of periods to reach specific value.',
    parameters: [{name: 'rate', description: 'The fixed interest rate per period.'}, {name: 'pv', description: 'The present value of the investment.'}, {name: 'fv', description: 'The desired future value of the investment.'}],
    examples: ['=PDURATION(0.05, 1000, 2000)', '=PDURATION(0.08, 500, 1500)'],
  },
  PMT: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the periodic payment for a loan.',
    parameters: [{name: 'rate', description: 'The interest rate per period.'}, {name: 'nper', description: 'The total number of payment periods.'}, {name: 'pv', description: 'The present value, i.e. the loan principal.'}, {name: 'fv', description: 'The future value, i.e. the desired cash balance after the last payment; defaults to 0.'}, {name: 'type', description: 'When payments are due: 0 for the end of each period, 1 for the beginning; defaults to 0.'}],
    examples: ['=PMT(0.05/12, 60, -20000)', '=PMT(0.04/12, 360, -200000, 0, 1)'],
  },
  PPMT: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Calculates the principal portion of a given loan payment.',
    parameters: [{name: 'rate', description: 'The interest rate per period.'}, {name: 'per', description: 'The period, between 1 and nper, for which the principal portion is calculated.'}, {name: 'nper', description: 'The total number of payment periods.'}, {name: 'pv', description: 'The present value, i.e. the loan principal.'}, {name: 'fv', description: 'The future value, i.e. the desired cash balance after the last payment; defaults to 0.'}, {name: 'type', description: 'When payments are due: 0 for the end of each period, 1 for the beginning; defaults to 0.'}],
    examples: ['=PPMT(0.05/12, 1, 60, 20000)', '=PPMT(0.04/12, 12, 360, 200000, 0, 1)'],
  },
  PV: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the present value of an investment.',
    parameters: [{name: 'rate', description: 'The interest rate per period.'}, {name: 'nper', description: 'The total number of payment periods.'}, {name: 'pmt', description: 'The payment made each period; paid-out amounts are negative.'}, {name: 'fv', description: 'The future value, i.e. the desired cash balance after the last payment; defaults to 0.'}, {name: 'type', description: 'When payments are due: 0 for the end of each period, 1 for the beginning; defaults to 0.'}],
    examples: ['=PV(0.05/12, 60, -100)', '=PV(0.04/12, 360, -1000, 0, 1)'],
  },
  RATE: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the interest rate per period of an annuity.',
    parameters: [{name: 'nper', description: 'The total number of payment periods.'}, {name: 'pmt', description: 'The payment made each period; paid-out amounts are negative.'}, {name: 'pv', description: 'The present value, i.e. the loan principal or initial investment.'}, {name: 'fv', description: 'The future value, i.e. the desired cash balance after the last payment; defaults to 0.'}, {name: 'type', description: 'When payments are due: 0 for the end of each period, 1 for the beginning; defaults to 0.'}, {name: 'guess', description: 'An estimated rate used as the starting point for the iterative calculation; defaults to 0.1 (10%).'}],
    examples: ['=RATE(60, -100, 5000)', '=RATE(360, -1000, 200000, 0, 0, 0.05)'],
  },
  RRI: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns an equivalent interest rate for the growth of an investment.',
    parameters: [{name: 'nper', description: 'The number of periods over which the investment grows.'}, {name: 'pv', description: 'The present value of the investment.'}, {name: 'fv', description: 'The future value of the investment.'}],
    examples: ['=RRI(10, 1000, 2000)', '=RRI(5, 5000, 6000)'],
  },
  SLN: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the depreciation of an asset for one period, based on a straight-line method.',
    parameters: [{name: 'cost', description: 'The initial cost of the asset.'}, {name: 'salvage', description: 'The value of the asset at the end of its depreciation.'}, {name: 'life', description: 'The number of periods over which the asset is depreciated.'}],
    examples: ['=SLN(10000, 1000, 6)', '=SLN(5000, 500, 10)'],
  },
  SYD: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the "sum-of-years" depreciation for an asset in a period.',
    parameters: [{name: 'cost', description: 'The initial cost of the asset.'}, {name: 'salvage', description: 'The value of the asset at the end of its depreciation.'}, {name: 'life', description: 'The number of periods over which the asset is depreciated.'}, {name: 'period', description: 'The period, in the same units as life, for which depreciation is calculated.'}],
    examples: ['=SYD(10000, 1000, 6, 2)', '=SYD(5000, 500, 10, 1)'],
  },
  TBILLEQ: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the bond-equivalent yield for a Treasury bill.',
    parameters: [{name: 'settlement', description: 'The settlement (purchase) date of the Treasury bill, as a date serial number.'}, {name: 'maturity', description: 'The maturity date of the Treasury bill, as a date serial number; must be within one year of settlement.'}, {name: 'discount', description: 'The discount rate of the Treasury bill.'}],
    examples: ['=TBILLEQ(DATE(2023,1,1), DATE(2023,6,1), 0.05)', '=TBILLEQ(A1, B1, 0.04)'],
  },
  TBILLPRICE: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the price per $100 face value for a Treasury bill.',
    parameters: [{name: 'settlement', description: 'The settlement (purchase) date of the Treasury bill, as a date serial number.'}, {name: 'maturity', description: 'The maturity date of the Treasury bill, as a date serial number; must be within one year of settlement.'}, {name: 'discount', description: 'The discount rate of the Treasury bill.'}],
    examples: ['=TBILLPRICE(DATE(2023,1,1), DATE(2023,6,1), 0.05)', '=TBILLPRICE(A1, B1, 0.04)'],
  },
  TBILLYIELD: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the yield for a Treasury bill.',
    parameters: [{name: 'settlement', description: 'The settlement (purchase) date of the Treasury bill, as a date serial number.'}, {name: 'maturity', description: 'The maturity date of the Treasury bill, as a date serial number; must be within one year of settlement.'}, {name: 'price', description: 'The price per $100 face value of the Treasury bill.'}],
    examples: ['=TBILLYIELD(DATE(2023,1,1), DATE(2023,6,1), 98)', '=TBILLYIELD(A1, B1, 99.5)'],
  },
  XNPV: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the net present value for a schedule of cash flows that is not necessarily periodic.',
    parameters: [{name: 'rate', description: 'The discount rate applied to the cash flows.'}, {name: 'payments', description: 'A range of cash flow values; paid-out amounts are negative, received amounts are positive.'}, {name: 'dates', description: 'A range of dates, one per payment, that must be the same length as payments; the first date is the reference point, and every other date must fall on or after it.'}],
    examples: ['=XNPV(0.09, A1:A4, B1:B4)', '=XNPV(0.1, C2:C6, D2:D6)'],
  },
  XIRR: {
    category: 'Financial',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the internal rate of return for a schedule of cash flows that is not necessarily periodic.',
    parameters: [{name: 'values', description: 'A range of cash flow values; must contain at least one negative and one positive value.'}, {name: 'dates', description: 'A range of payment dates, one per value in values and the same length; the first date is the reference point and every other date must fall on or after it.'}, {name: 'guess', description: 'An estimated rate used as the starting point for the iterative calculation; defaults to 0.1 (10%).'}],
    examples: ['=XIRR(A1:A4, B1:B4)', '=XIRR(A1:A5, B1:B5, 0.1)'],
  },
}
