/**
 * @license
 * Copyright (c) 2025 Handsoncode. All rights reserved.
 */

import {FunctionDoc} from '../FunctionDescription'

/**
 * Catalogue entries for the "Statistical" category. Generated from `docs/guide/built-in-functions.md` by
 * a one-time migration script (since removed); parameter descriptions are authored in a later phase.
 */
export const STATISTICAL_DOCS: Record<string, FunctionDoc> = {
  AVEDEV: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the average deviation of the arguments.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range included in the deviation calculation. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=AVEDEV(1, 2, 3)', '=AVEDEV(A1:A10)'],
  },
  AVERAGE: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the average of the arguments.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range whose values are averaged. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=AVERAGE(1, 2, 3)', '=AVERAGE(A1:A10)'],
  },
  AVERAGEA: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the average of the arguments.',
    parameters: [{name: 'value1', description: 'A value, cell reference, or range whose values are averaged; text and FALSE are treated as 0, and TRUE as 1. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=AVERAGEA(1, 2, TRUE())', '=AVERAGEA(A1:A10)'],
  },
  AVERAGEIF: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the arithmetic mean of all cells in a range that satisfy a given condition.',
    parameters: [{name: 'range', description: 'The range of cells tested against the criterion.'}, {name: 'criterion', description: 'The condition that selects which cells are averaged, e.g. ">5", "apples", or a cell reference.'}, {name: 'average_range', description: 'The range of cells to average. When omitted, the cells in Range are averaged instead.'}],
    examples: ['=AVERAGEIF(A1:A10, ">5")', '=AVERAGEIF(B1:B10, "apples", C1:C10)'],
  },
  BESSELI: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of Bessel function.',
    parameters: [{name: 'x', description: 'The value at which the modified Bessel function is evaluated.'}, {name: 'n', description: 'The order of the Bessel function; a non-negative integer.'}],
    examples: ['=BESSELI(1.5, 1)'],
  },
  BESSELJ: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of Bessel function.',
    parameters: [{name: 'x', description: 'The value at which the Bessel function is evaluated.'}, {name: 'n', description: 'The order of the Bessel function; a non-negative integer.'}],
    examples: ['=BESSELJ(1.9, 2)'],
  },
  BESSELK: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of Bessel function.',
    parameters: [{name: 'x', description: 'The value at which the modified Bessel function is evaluated; must be greater than 0.'}, {name: 'n', description: 'The order of the Bessel function; a non-negative integer.'}],
    examples: ['=BESSELK(1.5, 1)'],
  },
  BESSELY: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of Bessel function.',
    parameters: [{name: 'x', description: 'The value at which the Bessel function is evaluated; must be greater than 0.'}, {name: 'n', description: 'The order of the Bessel function; a non-negative integer.'}],
    examples: ['=BESSELY(1.5, 1)'],
  },
  'BETA.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the density of Beta distribution.',
    parameters: [{name: 'number1', description: 'The value at which to evaluate the distribution, within the interval bounded by Number4 and Number5.'}, {name: 'number2', description: 'The alpha shape parameter of the distribution; must be greater than 0.'}, {name: 'number3', description: 'The beta shape parameter of the distribution; must be greater than 0.'}, {name: 'boolean', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}, {name: 'number4', description: 'The lower bound of the interval of Number1; defaults to 0 when omitted.'}, {name: 'number5', description: 'The upper bound of the interval of Number1; defaults to 1 when omitted.'}],
    examples: ['=BETA.DIST(0.5, 2, 3, TRUE())', '=BETA.DIST(2, 2, 3, TRUE(), 0, 4)'],
  },
  'BETA.INV': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the inverse Beta distribution value.',
    parameters: [{name: 'number1', description: 'The probability associated with the Beta distribution, between 0 and 1.'}, {name: 'number2', description: 'The alpha shape parameter of the distribution; must be greater than 0.'}, {name: 'number3', description: 'The beta shape parameter of the distribution; must be greater than 0.'}, {name: 'number4', description: 'The lower bound of the interval of the result; defaults to 0 when omitted.'}, {name: 'number5', description: 'The upper bound of the interval of the result; defaults to 1 when omitted.'}],
    examples: ['=BETA.INV(0.5, 2, 3)', '=BETA.INV(0.25, 2, 3, 0, 4)'],
  },
  'BINOM.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of binomial distribution.',
    parameters: [{name: 'number1', description: 'The number of successes in the trials.'}, {name: 'number2', description: 'The total number of independent trials.'}, {name: 'number3', description: 'The probability of success on a single trial.'}, {name: 'boolean', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability mass function.'}],
    examples: ['=BINOM.DIST(3, 10, 0.5, FALSE())', '=BINOM.DIST(3, 10, 0.5, TRUE())'],
  },
  'BINOM.INV': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns inverse binomial distribution value.',
    parameters: [{name: 'number1', description: 'The total number of Bernoulli trials.'}, {name: 'number2', description: 'The probability of success on a single trial.'}, {name: 'number3', description: 'The criterion probability value; the function returns the smallest value for which the cumulative binomial distribution is greater than or equal to it.'}],
    examples: ['=BINOM.INV(10, 0.5, 0.75)'],
  },
  'CHISQ.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of chi-square distribution.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution; must be non-negative.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}, {name: 'mode', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}],
    examples: ['=CHISQ.DIST(2, 3, TRUE())', '=CHISQ.DIST(2, 3, FALSE())'],
  },
  'CHISQ.DIST.RT': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns probability of chi-square right-side distribution.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution; must be non-negative.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}],
    examples: ['=CHISQ.DIST.RT(2, 3)'],
  },
  'CHISQ.INV': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns inverse of chi-square distribution.',
    parameters: [{name: 'p', description: 'The probability associated with the chi-square distribution, between 0 and 1.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}],
    examples: ['=CHISQ.INV(0.9, 3)'],
  },
  'CHISQ.INV.RT': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns inverse of chi-square right-side distribution.',
    parameters: [{name: 'p', description: 'The right-tail probability associated with the chi-square distribution, between 0 and 1.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}],
    examples: ['=CHISQ.INV.RT(0.1, 3)'],
  },
  'CHISQ.TEST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns chisquared-test value for a dataset.',
    parameters: [{name: 'array1', description: 'The range of observed values.'}, {name: 'array2', description: 'The range of expected values, matching the size of Array1.'}],
    examples: ['=CHISQ.TEST(A1:B3, D1:E3)'],
  },
  'CONFIDENCE.NORM': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns upper confidence bound for normal distribution.',
    parameters: [{name: 'alpha', description: 'The significance level used to compute the confidence level, between 0 and 1.'}, {name: 'stdev', description: 'The population standard deviation; must be greater than 0.'}, {name: 'size', description: 'The sample size.'}],
    examples: ['=CONFIDENCE.NORM(0.05, 2.5, 50)'],
  },
  'CONFIDENCE.T': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns upper confidence bound for T distribution.',
    parameters: [{name: 'alpha', description: 'The significance level used to compute the confidence level, between 0 and 1.'}, {name: 'stdev', description: 'The sample standard deviation; must be greater than 0.'}, {name: 'size', description: 'The sample size.'}],
    examples: ['=CONFIDENCE.T(0.05, 2.5, 10)'],
  },
  CORREL: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the correlation coefficient between two data sets.',
    parameters: [{name: 'data1', description: 'The first range of numeric values.'}, {name: 'data2', description: 'The second range of numeric values, matching the size of Data1.'}],
    examples: ['=CORREL(A1:A10, B1:B10)'],
  },
  COUNT: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Counts how many numbers are in the list of arguments.',
    parameters: [{name: 'value1', description: 'A number, cell reference, or range counted if it contains a number. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=COUNT(1, 2, "text")', '=COUNT(A1:A10)'],
  },
  COUNTA: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Counts how many values are in the list of arguments.',
    parameters: [{name: 'value1', description: 'A value, cell reference, or range counted if it is not empty. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=COUNTA(A1:A10)', '=COUNTA(1, "text", TRUE())'],
  },
  COUNTBLANK: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the number of empty cells.',
    parameters: [{name: 'range', description: 'A value, cell reference, or range checked for emptiness. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=COUNTBLANK(A1:A10)', '=COUNTBLANK(A1:A10, C1:C10)'],
  },
  COUNTIF: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the number of cells that meet with certain criteria within a cell range.',
    parameters: [{name: 'range', description: 'The range of cells tested against the criteria.'}, {name: 'criteria', description: 'The condition that selects which cells are counted, e.g. ">5", "apples", or a cell reference.'}],
    examples: ['=COUNTIF(A1:A10, ">5")', '=COUNTIF(B1:B10, "apples")'],
  },
  COUNTIFS: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the count of rows or columns that meet criteria in multiple ranges.',
    parameters: [{name: 'range1', description: 'A range of cells tested against the paired criterion. Further range/criterion pairs can be passed as additional arguments, and only cells meeting every criterion are counted.'}, {name: 'criterion1', description: 'The condition applied to the preceding range, e.g. ">5", "apples", or a cell reference.'}],
    examples: ['=COUNTIFS(A1:A10, ">5")', '=COUNTIFS(A1:A10, ">5", B1:B10, "apples")'],
  },
  'COVARIANCE.P': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the covariance between two data sets, population normalized.',
    parameters: [{name: 'data1', description: 'The first range of numeric values.'}, {name: 'data2', description: 'The second range of numeric values, matching the size of Data1.'}],
    examples: ['=COVARIANCE.P(A1:A10, B1:B10)'],
  },
  'COVARIANCE.S': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the covariance between two data sets, sample normalized.',
    parameters: [{name: 'data1', description: 'The first range of numeric values.'}, {name: 'data2', description: 'The second range of numeric values, matching the size of Data1.'}],
    examples: ['=COVARIANCE.S(A1:A10, B1:B10)'],
  },
  DEVSQ: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns sum of squared deviations.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range included in the sum of squared deviations. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=DEVSQ(1, 2, 3)', '=DEVSQ(A1:A10)'],
  },
  'EXPON.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of a exponential distribution.',
    parameters: [{name: 'number1', description: 'The value at which to evaluate the distribution; must be non-negative.'}, {name: 'number2', description: 'The lambda rate parameter of the distribution; must be greater than 0.'}, {name: 'boolean', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}],
    examples: ['=EXPON.DIST(1, 0.5, TRUE())', '=EXPON.DIST(1, 0.5, FALSE())'],
  },
  'F.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of F distribution.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution; must be non-negative.'}, {name: 'degree1', description: 'The numerator degrees of freedom.'}, {name: 'degree2', description: 'The denominator degrees of freedom.'}, {name: 'mode', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}],
    examples: ['=F.DIST(2, 3, 10, TRUE())', '=F.DIST(2, 3, 10, FALSE())'],
  },
  'F.DIST.RT': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns probability of F right-side distribution.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution; must be non-negative.'}, {name: 'degree1', description: 'The numerator degrees of freedom.'}, {name: 'degree2', description: 'The denominator degrees of freedom.'}],
    examples: ['=F.DIST.RT(2, 3, 10)'],
  },
  'F.INV': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns inverse of F distribution.',
    parameters: [{name: 'p', description: 'The probability associated with the F distribution, between 0 and 1.'}, {name: 'degree1', description: 'The numerator degrees of freedom.'}, {name: 'degree2', description: 'The denominator degrees of freedom.'}],
    examples: ['=F.INV(0.9, 3, 10)'],
  },
  'F.INV.RT': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns inverse of F right-side distribution.',
    parameters: [{name: 'p', description: 'The right-tail probability associated with the F distribution, between 0 and 1.'}, {name: 'degree1', description: 'The numerator degrees of freedom.'}, {name: 'degree2', description: 'The denominator degrees of freedom.'}],
    examples: ['=F.INV.RT(0.1, 3, 10)'],
  },
  'F.TEST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns f-test value for a dataset.',
    parameters: [{name: 'array1', description: 'The first range or array of sample values.'}, {name: 'array2', description: 'The second range or array of sample values.'}],
    examples: ['=F.TEST(A1:A10, B1:B10)'],
  },
  FISHER: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns Fisher transformation value.',
    parameters: [{name: 'number', description: 'The value to transform; must be greater than -1 and less than 1.'}],
    examples: ['=FISHER(0.5)'],
  },
  FISHERINV: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns inverse Fisher transformation value.',
    parameters: [{name: 'number', description: 'The value of the Fisher transformation to invert.'}],
    examples: ['=FISHERINV(0.5)'],
  },
  GAMMA: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of Gamma function.',
    parameters: [{name: 'number', description: 'The value at which to evaluate the Gamma function; must not be zero or a negative integer.'}],
    examples: ['=GAMMA(5)'],
  },
  'GAMMA.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of Gamma distribution.',
    parameters: [{name: 'number1', description: 'The value at which to evaluate the distribution; must be non-negative.'}, {name: 'number2', description: 'The alpha shape parameter of the distribution; must be greater than 0.'}, {name: 'number3', description: 'The beta scale parameter of the distribution; must be greater than 0.'}, {name: 'boolean', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}],
    examples: ['=GAMMA.DIST(2, 1, 2, TRUE())', '=GAMMA.DIST(2, 1, 2, FALSE())'],
  },
  'GAMMA.INV': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns inverse Gamma distribution value.',
    parameters: [{name: 'number1', description: 'The probability associated with the Gamma distribution, between 0 and 1.'}, {name: 'number2', description: 'The alpha shape parameter of the distribution; must be greater than 0.'}, {name: 'number3', description: 'The beta scale parameter of the distribution; must be greater than 0.'}],
    examples: ['=GAMMA.INV(0.5, 1, 2)'],
  },
  GAMMALN: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns natural logarithm of Gamma function.',
    parameters: [{name: 'number', description: 'The value at which to evaluate the natural logarithm of the Gamma function; must be greater than 0.'}],
    examples: ['=GAMMALN(5)'],
  },
  GAUSS: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the probability of gaussian variable falling more than this many times standard deviation from mean.',
    parameters: [{name: 'number', description: 'The number of standard deviations from the mean, Z, of a standard normal variable.'}],
    examples: ['=GAUSS(2)'],
  },
  GEOMEAN: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the geometric average.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range to average geometrically; all values must be positive, otherwise the result is #NUM!. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=GEOMEAN(1, 2, 3)', '=GEOMEAN(A1:A10)'],
  },
  HARMEAN: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the harmonic average.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range to average harmonically; all values must be positive, otherwise the result is #NUM!. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=HARMEAN(1, 2, 4)', '=HARMEAN(A1:A10)'],
  },
  'HYPGEOM.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of hypergeometric distribution.',
    parameters: [{name: 'number1', description: 'The number of successes in the sample.'}, {name: 'number2', description: 'The size of the sample.'}, {name: 'number3', description: 'The number of successes in the population.'}, {name: 'number4', description: 'The size of the population.'}, {name: 'boolean', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability mass function.'}],
    examples: ['=HYPGEOM.DIST(1, 4, 8, 20, FALSE())', '=HYPGEOM.DIST(1, 4, 8, 20, TRUE())'],
  },
  LARGE: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns k-th largest value in a range.',
    parameters: [{name: 'range', description: 'The range of values to evaluate.'}, {name: 'k', description: 'The position, from the largest, of the value to return; 1 returns the largest value.'}],
    examples: ['=LARGE(A1:A10, 1)', '=LARGE(A1:A10, 3)'],
  },
  'LOGNORM.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of lognormal distribution.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution; must be greater than 0.'}, {name: 'mean', description: 'The mean of the natural logarithm of the distribution.'}, {name: 'stddev', description: 'The standard deviation of the natural logarithm of the distribution; must be greater than 0.'}, {name: 'mode', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}],
    examples: ['=LOGNORM.DIST(4, 0, 1, TRUE())', '=LOGNORM.DIST(4, 0, 1, FALSE())'],
  },
  'LOGNORM.INV': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of inverse lognormal distribution.',
    parameters: [{name: 'p', description: 'The probability associated with the lognormal distribution, between 0 and 1.'}, {name: 'mean', description: 'The mean of the natural logarithm of the distribution.'}, {name: 'stddev', description: 'The standard deviation of the natural logarithm of the distribution; must be greater than 0.'}],
    examples: ['=LOGNORM.INV(0.5, 0, 1)'],
  },
  MAX: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the maximum value in a list of arguments.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range compared against the current maximum. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=MAX(1, 2, 3)', '=MAX(A1:A10)'],
  },
  MAXA: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the maximum value in a list of arguments.',
    parameters: [{name: 'value1', description: 'A value, cell reference, or range compared against the current maximum; text and FALSE are treated as 0, and TRUE as 1. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=MAXA(1, 2, TRUE())', '=MAXA(A1:A10)'],
  },
  MAXIFS: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the maximum value of the cells in a range that meet a set of criteria.',
    parameters: [{name: 'max_range', description: 'The range of cells to evaluate for the maximum.'}, {name: 'criterion_range1', description: 'A range of cells tested against the paired criterion. Further range/criterion pairs can be passed as additional arguments, and only cells meeting every criterion are considered.'}, {name: 'criterion1', description: 'The condition applied to the preceding range, e.g. ">5", "apples", or a cell reference.'}],
    examples: ['=MAXIFS(A1:A10, B1:B10, ">5")', '=MAXIFS(A1:A10, B1:B10, ">5", C1:C10, "apples")'],
  },
  MEDIAN: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the median of a set of numbers.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range included in the median calculation. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=MEDIAN(1, 2, 3)', '=MEDIAN(A1:A10)'],
  },
  MIN: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the minimum value in a list of arguments.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range compared against the current minimum. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=MIN(1, 2, 3)', '=MIN(A1:A10)'],
  },
  MINA: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the minimum value in a list of arguments.',
    parameters: [{name: 'value1', description: 'A value, cell reference, or range compared against the current minimum; text and FALSE are treated as 0, and TRUE as 1. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=MINA(1, 2, FALSE())', '=MINA(A1:A10)'],
  },
  MINIFS: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the minimum value of the cells in a range that meet a set of criteria.',
    parameters: [{name: 'min_range', description: 'The range of cells to evaluate for the minimum.'}, {name: 'criterion_range1', description: 'A range of cells tested against the paired criterion. Further range/criterion pairs can be passed as additional arguments, and only cells meeting every criterion are considered.'}, {name: 'criterion1', description: 'The condition applied to the preceding range, e.g. ">5", "apples", or a cell reference.'}],
    examples: ['=MINIFS(A1:A10, B1:B10, ">5")', '=MINIFS(A1:A10, B1:B10, ">5", C1:C10, "apples")'],
  },
  'NEGBINOM.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of negative binomial distribution.',
    parameters: [{name: 'number1', description: 'The number of failures.'}, {name: 'number2', description: 'The threshold number of successes.'}, {name: 'number3', description: 'The probability of success on a single trial.'}, {name: 'mode', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability mass function.'}],
    examples: ['=NEGBINOM.DIST(3, 5, 0.5, FALSE())', '=NEGBINOM.DIST(3, 5, 0.5, TRUE())'],
  },
  'NORM.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of normal distribution.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution.'}, {name: 'mean', description: 'The arithmetic mean of the distribution.'}, {name: 'stddev', description: 'The standard deviation of the distribution; must be greater than 0.'}, {name: 'mode', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}],
    examples: ['=NORM.DIST(1, 0, 1, TRUE())', '=NORM.DIST(1, 0, 1, FALSE())'],
  },
  'NORM.INV': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of inverse normal distribution.',
    parameters: [{name: 'p', description: 'The probability associated with the normal distribution, between 0 and 1.'}, {name: 'mean', description: 'The arithmetic mean of the distribution.'}, {name: 'stddev', description: 'The standard deviation of the distribution; must be greater than 0.'}],
    examples: ['=NORM.INV(0.5, 0, 1)'],
  },
  'NORM.S.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of normal distribution.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the standard normal distribution.'}, {name: 'mode', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}],
    examples: ['=NORM.S.DIST(1, TRUE())', '=NORM.S.DIST(1, FALSE())'],
  },
  'NORM.S.INV': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns value of inverse normal distribution.',
    parameters: [{name: 'p', description: 'The probability associated with the standard normal distribution, between 0 and 1.'}],
    examples: ['=NORM.S.INV(0.5)'],
  },
  'PERCENTILE.EXC': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the k-th percentile of values in a range, exclusive of 0 and 1.',
    parameters: [{name: 'data', description: 'The range of values to evaluate.'}, {name: 'k', description: 'The percentile to return, exclusive of 0 and 1, e.g. 0.25.'}],
    examples: ['=PERCENTILE.EXC(A1:A10, 0.25)'],
  },
  'PERCENTILE.INC': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the k-th percentile of values in a range, inclusive of 0 and 1.',
    parameters: [{name: 'data', description: 'The range of values to evaluate.'}, {name: 'k', description: 'The percentile to return, inclusive of 0 and 1, e.g. 0.9.'}],
    examples: ['=PERCENTILE.INC(A1:A10, 0.9)'],
  },
  PHI: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns probability density of normal distribution.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the standard normal probability density function.'}],
    examples: ['=PHI(1)'],
  },
  'POISSON.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of Poisson distribution.',
    parameters: [{name: 'x', description: 'The number of events; must be non-negative.'}, {name: 'mean', description: 'The expected number of events; must be non-negative.'}, {name: 'mode', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability mass function.'}],
    examples: ['=POISSON.DIST(3, 5, FALSE())', '=POISSON.DIST(3, 5, TRUE())'],
  },
  'QUARTILE.EXC': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the quartile of a data set, based on exclusive percentile values.',
    parameters: [{name: 'data', description: 'The range of values to evaluate.'}, {name: 'quart', description: 'The quartile to return, exclusive of 0 and 4, an integer from 1 to 3.'}],
    examples: ['=QUARTILE.EXC(A1:A10, 1)'],
  },
  'QUARTILE.INC': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the quartile of a data set, based on inclusive percentile values.',
    parameters: [{name: 'data', description: 'The range of values to evaluate.'}, {name: 'quart', description: 'The quartile to return, inclusive of 0 and 4, an integer from 0 to 4.'}],
    examples: ['=QUARTILE.INC(A1:A10, 3)'],
  },
  RSQ: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the squared correlation coefficient between two data sets.',
    parameters: [{name: 'data1', description: 'The range of dependent (y) values.'}, {name: 'data2', description: 'The range of independent (x) values, matching the size of Data1.'}],
    examples: ['=RSQ(A1:A10, B1:B10)'],
  },
  SKEW: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns skewness of a sample.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range included in the sample skewness calculation. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=SKEW(1, 2, 3, 10)', '=SKEW(A1:A10)'],
  },
  'SKEW.P': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns skewness of a population.',
    parameters: [{name: 'number1', description: 'A number, cell reference, or range included in the population skewness calculation. Further numbers or ranges can be passed as additional arguments.'}],
    examples: ['=SKEW.P(1, 2, 3, 10)', '=SKEW.P(A1:A10)'],
  },
  SLOPE: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns the slope of a linear regression line.',
    parameters: [{name: 'array1', description: 'The range of dependent (y) values.'}, {name: 'array2', description: 'The range of independent (x) values, matching the size of Array1.'}],
    examples: ['=SLOPE(A1:A10, B1:B10)'],
  },
  SMALL: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns k-th smallest value in a range.',
    parameters: [{name: 'range', description: 'The range of values to evaluate.'}, {name: 'k', description: 'The position, from the smallest, of the value to return; 1 returns the smallest value.'}],
    examples: ['=SMALL(A1:A10, 1)', '=SMALL(A1:A10, 3)'],
  },
  STANDARDIZE: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns normalized value wrt expected value and standard deviation.',
    parameters: [{name: 'x', description: 'The value to normalize.'}, {name: 'mean', description: 'The arithmetic mean of the distribution.'}, {name: 'stddev', description: 'The standard deviation of the distribution; must be greater than 0.'}],
    examples: ['=STANDARDIZE(5, 3, 2)'],
  },
  'STDEV.P': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns standard deviation of a population.',
    parameters: [{name: 'value1', description: 'A number, cell reference, or range included in the population standard deviation calculation. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=STDEV.P(1, 2, 3)', '=STDEV.P(A1:A10)'],
  },
  'STDEV.S': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns standard deviation of a sample.',
    parameters: [{name: 'value1', description: 'A number, cell reference, or range included in the sample standard deviation calculation. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=STDEV.S(1, 2, 3)', '=STDEV.S(A1:A10)'],
  },
  STDEVA: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns standard deviation of a sample.',
    parameters: [{name: 'value1', description: 'A value, cell reference, or range included in the sample standard deviation calculation; text and FALSE are treated as 0, and TRUE as 1. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=STDEVA(1, TRUE(), 3)', '=STDEVA(A1:A10)'],
  },
  STDEVPA: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns standard deviation of a population.',
    parameters: [{name: 'value1', description: 'A value, cell reference, or range included in the population standard deviation calculation; text and FALSE are treated as 0, and TRUE as 1. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=STDEVPA(1, TRUE(), 3)', '=STDEVPA(A1:A10)'],
  },
  STEYX: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns standard error for predicted of the predicted y value for each x value.',
    parameters: [{name: 'array1', description: 'The range of dependent (y) values.'}, {name: 'array2', description: 'The range of independent (x) values, matching the size of Array1.'}],
    examples: ['=STEYX(A1:A10, B1:B10)'],
  },
  'T.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of Student-t distribution.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}, {name: 'mode', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}],
    examples: ['=T.DIST(1, 10, TRUE())', '=T.DIST(1, 10, FALSE())'],
  },
  'T.DIST.2T': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of Student-t distribution, both-sided.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution; must be non-negative.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}],
    examples: ['=T.DIST.2T(1, 10)'],
  },
  'T.DIST.RT': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of Student-t distribution, right-tailed.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}],
    examples: ['=T.DIST.RT(1, 10)'],
  },
  'T.INV': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns inverse Student-t distribution.',
    parameters: [{name: 'p', description: 'The probability associated with the left-tailed Student-t distribution, between 0 and 1.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}],
    examples: ['=T.INV(0.9, 10)'],
  },
  'T.INV.2T': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns inverse Student-t distribution, both-sided.',
    parameters: [{name: 'p', description: 'The probability associated with the two-tailed Student-t distribution, between 0 and 1.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}],
    examples: ['=T.INV.2T(0.1, 10)'],
  },
  'T.TEST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns t-test value for a dataset.',
    parameters: [{name: 'array1', description: 'The first range or array of sample values.'}, {name: 'array2', description: 'The second range or array of sample values.'}, {name: 'tails', description: 'The number of distribution tails to use: 1 for a one-tailed test, or 2 for a two-tailed test.'}, {name: 'type', description: 'The kind of t-test to perform: 1 for paired, 2 for two-sample equal variance, or 3 for two-sample unequal variance.'}],
    examples: ['=T.TEST(A1:A10, B1:B10, 2, 1)'],
  },
  TDIST: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of Student-t distribution, both-sided or right-tailed.',
    parameters: [{name: 'x', description: 'The value at which to evaluate the distribution; must be non-negative.'}, {name: 'degrees', description: 'The number of degrees of freedom.'}, {name: 'mode', description: 'The number of distribution tails to return: 1 for right-tailed, or 2 for two-tailed.'}],
    examples: ['=TDIST(1, 10, 1)', '=TDIST(1, 10, 2)'],
  },
  'VAR.P': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns variance of a population.',
    parameters: [{name: 'value1', description: 'A number, cell reference, or range included in the population variance calculation. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=VAR.P(1, 2, 3)', '=VAR.P(A1:A10)'],
  },
  'VAR.S': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns variance of a sample.',
    parameters: [{name: 'value1', description: 'A number, cell reference, or range included in the sample variance calculation. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=VAR.S(1, 2, 3)', '=VAR.S(A1:A10)'],
  },
  VARA: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns variance of a sample.',
    parameters: [{name: 'value1', description: 'A value, cell reference, or range included in the sample variance calculation; text and FALSE are treated as 0, and TRUE as 1. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=VARA(1, TRUE(), 3)', '=VARA(A1:A10)'],
  },
  VARPA: {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns variance of a population.',
    parameters: [{name: 'value1', description: 'A value, cell reference, or range included in the population variance calculation; text and FALSE are treated as 0, and TRUE as 1. Further values or ranges can be passed as additional arguments.'}],
    examples: ['=VARPA(1, TRUE(), 3)', '=VARPA(A1:A10)'],
  },
  'WEIBULL.DIST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns density of Weibull distribution.',
    parameters: [{name: 'number1', description: 'The value at which to evaluate the distribution; must be non-negative.'}, {name: 'number2', description: 'The alpha shape parameter of the distribution; must be greater than 0.'}, {name: 'number3', description: 'The beta scale parameter of the distribution; must be greater than 0.'}, {name: 'boolean', description: 'TRUE returns the cumulative distribution function; FALSE returns the probability density function.'}],
    examples: ['=WEIBULL.DIST(2, 1, 2, TRUE())', '=WEIBULL.DIST(2, 1, 2, FALSE())'],
  },
  'Z.TEST': {
    category: 'Statistical',
    documentationUrl: 'https://hyperformula.handsontable.com/docs/guide/built-in-functions.html',
    shortDescription: 'Returns z-test value for a dataset.',
    parameters: [{name: 'array', description: 'The range or array of sample values to test against.'}, {name: 'x', description: 'The value to test.'}, {name: 'sigma', description: 'The known population standard deviation; when omitted, the sample standard deviation of Array is used instead.'}],
    examples: ['=Z.TEST(A1:A10, 5)', '=Z.TEST(A1:A10, 5, 2)'],
  },
}
