name: Security

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ '12' ]
        os: [ 'ubuntu-latest' ]
    name: AUDIT
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598 # https://github.com/actions/checkout/releases/tag/v2.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@83c9f7a7df54d6b57455f7c57ac414f2ae5fb8de # https://github.com/actions/setup-node/releases/tag/v1.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run audit
        run: |
          npm audit
