name: Publish

on:
  push:
    branches:
      - docs
      - develop

jobs:
  docs:
    name: DOCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598 # https://github.com/actions/checkout/releases/tag/v2.0.0
      - name: Install dependencies
        run: |
          npm ci
      - name: Build docs
        run: |
          npm run docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@ba0b7df03e25ff29c924be8149041119e9421ea6 # https://github.com/peaceiris/actions-gh-pages/releases/tag/v3.5.6
        with:
          publish_dir: docs/.vuepress/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
