name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize # the head branch is updated from the base branch, new commits are pushed to the head branch, or the base branch is changed

jobs:
  performance-test:
    strategy:
      matrix:
        node-version: [ '16' ]
        os: [ 'ubuntu-latest' ]
    name: performance-test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d # https://github.com/actions/setup-node/releases/tag/v1.4.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: (develop) Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # https://github.com/actions/checkout/releases/tag/v2.3.4
        with:
          ref: develop

      - name: (develop) Install dependencies
        run: |
          npm ci

      - name: (develop) Run performance tests
        run: |
          npm run benchmark:write-to-file develop.json

      - name: (current) Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # https://github.com/actions/checkout/releases/tag/v2.3.4

      - name: (current) Install dependencies
        run: |
          npm ci

      - name: (current) Run performance tests
        run: |
          npm run benchmark:write-to-file current.json

      - name: Compare the results
        run: |
          npm run benchmark:compare-benchmarks develop.json current.json performance-report.txt

      - name: Publish a comment in the PR
        uses: marocchino/sticky-pull-request-comment@6804b5ad49d19c10c9ae7cf5057352f7ff333f31 # https://github.com/marocchino/sticky-pull-request-comment/tree/v1.6.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: performance-report.txt